apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: 675789572615.dkr.ecr.ap-south-1.amazonaws.com/tripneo/chat-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          envFrom:
            - secretRef:
                name: chat-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP
