name: payment-service-cicd

on:
  push:
    branches:
      - main
    paths:
      - 'payment-service/**'
      - '.github/workflows/payment-service-cicd.yml'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'junaid9001'
    defaults:
      run:
        working-directory: ./payment-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run Unit Tests
        run: |
          go mod download
          go test ./...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tripneo/payment-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: tripneo/payment-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws eks update-kubeconfig --name tripneo-cluster --region ap-south-1
          kubectl set image deployment/payment-service-deployment payment-service=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl rollout status deployment/payment-service-deployment --timeout=120s
